# Generated by Junie: add host field to Event
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(blank=True, help_text='Primary host of the event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_hosting', to='Members.member'),
        ),
    ]
