# Generated by Django 5.2.6

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0007_child_child_id_child_created_at_child_profile_image_and_more'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_led', to='Members.member')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='units.unit')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('unit', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DepartmentMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='units.department')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_memberships', to='Members.member')),
            ],
            options={
                'ordering': ['-joined_date'],
                'unique_together': {('department', 'member', 'is_active')},
            },
        ),
    ]
