# Generated by AI assistant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='is_special_staff',
            field=models.BooleanField(default=False, help_text='Special Staff positions work directly for the Fleet Commander'),
        ),
    ]
