# Generated by Django 5.2.6 on 2025-09-19 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_departments'),
        ('units', '0007_position_special_staff'),
    ]

    operations = [
    ]
