# Generated by Django 5.2.6 on 2025-09-16 13:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('abbreviation', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paygrade', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Paygrade must be in format X-Y (e.g. E-1, O-3)', regex='^[A-Z]-\\d+$')])),
                ('short_name', models.CharField(max_length=50)),
                ('long_name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(help_text='Order of rank for sorting purposes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rank',
                'verbose_name_plural': 'Ranks',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='rank.branch')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='rank.genre')),
            ],
            options={
                'unique_together': {('name', 'genre', 'branch')},
            },
        ),
        migrations.CreateModel(
            name='RankSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_settings', to='rank.branch')),
                ('default_genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_settings', to='rank.genre')),
                ('default_paygrade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_settings', to='rank.rank')),
                ('default_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_settings', to='rank.theme')),
            ],
            options={
                'verbose_name': 'Rank Settings',
                'verbose_name_plural': 'Rank Settings',
            },
        ),
        migrations.CreateModel(
            name='RankImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rank_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rank.rank')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_images', to='rank.theme')),
            ],
            options={
                'unique_together': {('rank', 'theme')},
            },
        ),
    ]
# Generated by Django 4.2.6

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Members', '0002_member_theme_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('abbreviation', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paygrade', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Paygrade must be in format X-Y (e.g. E-1, O-3)', regex='^[A-Z]-\\d+$')])),
                ('short_name', models.CharField(max_length=50)),
                ('long_name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(help_text='Order of rank for sorting purposes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rank',
                'verbose_name_plural': 'Ranks',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='rank.branch')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='rank.genre')),
            ],
            options={
                'unique_together': {('name', 'genre', 'branch')},
            },
        ),
        migrations.CreateModel(
            name='RankSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_settings', to='rank.branch')),
                ('default_genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_settings', to='rank.genre')),
                ('default_paygrade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_settings', to='rank.rank')),
                ('default_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_settings', to='rank.theme')),
            ],
            options={
                'verbose_name': 'Rank Settings',
                'verbose_name_plural': 'Rank Settings',
            },
        ),
        migrations.CreateModel(
            name='RankImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rank_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rank.rank')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_images', to='rank.theme')),
            ],
            options={
                'unique_together': {('rank', 'theme')},
            },
        ),
        migrations.CreateModel(
            name='MemberRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rank_assignments', to=settings.AUTH_USER_MODEL)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rank_association', to='Members.member')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_associations', to='rank.rank')),
            ],
            options={
                'verbose_name': 'Member Rank',
                'verbose_name_plural': 'Member Ranks',
                'ordering': ['-effective_date'],
            },
        ),
    ]