# Generated by Django 4.2.6

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberrank',
            name='preferred_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_preferences', to='rank.theme'),
        ),
    ]
