# Generated by Django 4.2.6

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0009_memberrankhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberrankhistory',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theme_history', to='rank.theme'),
        ),
        migrations.AddField(
            model_name='memberrankhistory',
            name='previous_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsequent_theme_history', to='rank.theme'),
        ),
        migrations.AddField(
            model_name='memberrankhistory',
            name='change_type',
            field=models.CharField(choices=[('rank', 'Rank Change'), ('theme', 'Theme Change'), ('both', 'Rank & Theme Change'), ('initial', 'Initial Assignment')], default='rank', max_length=20),
        ),
    ]
