# Generated by Django 4.2.6

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Members', '0002_member_theme_preference'),
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRankHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rank_history_assignments', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_history', to='Members.member')),
                ('previous_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsequent_rank_history', to='rank.rank')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_history', to='rank.rank')),
            ],
            options={
                'verbose_name': 'Member Rank History',
                'verbose_name_plural': 'Member Rank History',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
    ]
