# Generated by Django 5.2.6

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Members', '0007_child_child_id_child_created_at_child_profile_image_and_more'),
        ('rank', '0012_merge_20250916_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_rank_assignments', to=settings.AUTH_USER_MODEL)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child_rank_association', to='Members.child')),
                ('preferred_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_preferences', to='rank.theme')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_associations', to='rank.rank')),
            ],
            options={
                'verbose_name': 'Child Rank',
                'verbose_name_plural': 'Child Ranks',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='ChildRankHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('rank', 'Rank Change'), ('theme', 'Theme Change'), ('both', 'Rank & Theme Change'), ('initial', 'Initial Assignment')], default='rank', max_length=20)),
                ('effective_date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_rank_history_assignments', to=settings.AUTH_USER_MODEL)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_history', to='Members.child')),
                ('previous_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsequent_child_rank_history', to='rank.rank')),
                ('previous_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsequent_child_theme_history', to='rank.theme')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_rank_history', to='rank.rank')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_theme_history', to='rank.theme')),
            ],
            options={
                'verbose_name': 'Child Rank History',
                'verbose_name_plural': 'Child Rank History',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
    ]
