# Generated by Django 5.2.6 on 2025-09-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0002_member_theme_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10),
        ),
    ]
