# Generated by Django 5.2.6 on 2025-09-17 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0004_faqcategory_alter_member_theme_preference_faq'),
        ('Members', 'add_profile_image'),
    ]

    operations = [
    ]
