# Generated by Django 5.2.6 on 2025-09-17 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0005_merge_20250917_1630'),
        ('Members', 'add_image_validators'),
    ]

    operations = [
    ]
