# Generated by Django 5.2.6 on 2025-09-17 18:06

import Members.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0006_merge_0005_merge_20250917_1630_add_image_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='child_id',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='child',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Upload a profile image (JPG, PNG, or GIF, max 5MB)', null=True, upload_to='child_profile_images/', validators=[Members.validators.validate_image_extension, Members.validators.validate_image_size]),
        ),
        migrations.AddField(
            model_name='child',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='child',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Upload a profile image (JPG, PNG, or GIF, max 5MB)', null=True, upload_to='profile_images/', validators=[Members.validators.validate_image_extension, Members.validators.validate_image_size]),
        ),
    ]
